# Site Information

name: Digital Humanities Research Institute 
description: Digital Humanities Research Institute
url: dhinstitutes.org
title: Digital Humanities Research Institute
host-institution: The Faculty Center, Arkansas State University
host-institution-url: http://www.astate.edu/a/ittc/
date-range: May X-X, 2019
author:
  name: Dr. Andrea Davis
  email: andavis@astate.edu
  url: https://andrea-davis.com
  twitter: DrDreaDavis
  address: 
  description: Focused on the theme “Heritage in the Digital Age,” DHRI builds on college-wide interest and expertise in Heritage Studies to create a community of digital humanities practice at Arkansas State University.



# A list of courses that appears on the curriculum page
# Note that link-reference should be one short, descriptive word
courses:

  - name: Digital Publishing
    url:
    link-reference: publishing
    description: This session will introduce participants to two digital publishing platforms— Scalar and Omeka. Scalar and Omeka are two of the most commonly-used free and open-source publishing platforms for scholarly communication. In addition to learning the basics and basic differences of each platform, participants will begin to build a project on one of the platforms.  This workshop is geared towards beginners – no prior experience with either publishing platform is necessary.
  - name: Digital Design
    url: https://github.com/DHRI-Curriculum/html-css
    link-reference: design
    description: This session will introduce attendees to two mark-up languages- HTML and CSS. These are two of the most commonly-used languages in rendering information on the web today. In addition to learning the basics and basic differences of each language, participants will apply best practices in digital design by customizing a Scalar or Omeka project using HTML and CSS. Beyond learning HTML and CSS, users will leave the workshop with a clearer understanding of how the internet works. This workshop is geared towards beginners – no prior experience with either language or website-building is necessary.
  - name: Digital Preservation
    url:
    link-reference: preservation
    description: 
  - name: Crowd Sourcing
    url: 
    link-reference: crowd
    description: 
  - name: Ethics
    url: https://github.com/DHRI-Curriculum/ethics
    link-reference:  ethics
    description: This discussion-based workshop will address an array of ethical questions and concerns for community-based research and teaching. In addressing issues of confidentiality, inclusion, participation, and accessibility, this workshop will first provide a general overview of ethics for institutional research compliance —including the Belmont Report and Institutional Review Board — and then delve into ethical issues that extend beyond institutional purview.
  - name: Project Planning
    url: https://github.com/DHRI-Curriculum/project-lab
    link-reference: project
    description: What separates projects that turn into something from those that stall out and go nowhere is the formulation (and constant revision and adaptation) of a reasonable, informed, and purposeful project plan. During this session, participants will be introduced to sound project development and management practices. Starting with an end goal in mind, an articulation of the needs and opportunities, collaborators, audience, resources, and work plan, participants will draft a one to three page proposal for their DH projects.
  - name: Project Lab
    link-reference: lab
    description: This session will provide participants with time to work independently or—if desired—in groups to begin designing their own digital heritage projects for research or teaching. Instructors will be on hand to answer questions and provide feedback.
  - name: Presentations
    link-reference: presentations
    description: Each participant will present a five-minute proposal for a digital heritage project.
# this tells Jekyll to build the site in the "docs"
# directory, which is ideal for hosting by GitHub Pages
destination: docs


# Files that won't be included in the compiled version of the site
exclude:
  - '*.sh'
  - CNAME
  - bower_components
  - node_modules
  - _images
  - '.*'
  - 'gulpfile.js'
  - 'build_vendor.js'
  - 'get_data.js'
  - 'README.md'

# _config.stage.yml overwrites these options when you run locally
future: false
limit_posts: 10 # Only make the last 10 posts so generating isn't slow
show_drafts: false

#required by github-pages
lsi: false # Disables the more accurate related posts
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
