# Site Information

name: Digital Humanities Research Institute 
description: Digital Humanities Research Institute
url: dhinstitutes.org
title: Digital Humanities Research Institute
host-institution: The Faculty Center, Arkansas State University
host-institution-url: http://www.astate.edu/a/ittc/
date-range: May X-X, 2019
author:
  name: Dr. Andrea Davis
  email: andavis@astate.edu
  url: https://andrea-davis.com
  twitter: DrDreaDavis
  address: 
  description: Focused on the theme “Heritage in the Digital Age,” DHRI builds on college-wide interest and expertise in Heritage Studies to create a community of digital humanities practice at Arkansas State University.



# A list of courses that appears on the curriculum page
# Note that link-reference should be one short, descriptive word
courses:

  - name: Digital Publishing
    url:
    link-reference: publishing
    description: This session will introduce participants to two digital publishing platforms—Scalar and Omeka. Scalar and Omeka are two of the most commonly-used free and open-source publishing platforms for scholarly exhibits and communication. In addition to learning the basics and basic differences of each platform, participants will begin to build a project on one of the platforms.  This workshop is geared towards beginners – no prior experience with either publishing platform is necessary. More advanced participants will have the opportunity to customize their site using the markup languages HTML and CSS. 
  - name: Digital Heritage Preservation
    url: 
    link-reference: preservation
    description: Digital preservation requires adequate planning, description and modes of access. During this session, participants will be introduced to the principles of sound collection development and learn how to arrange and describe content so that it is legible and discoverable to users. Using the site built during the previous session, participants will begin to create a digital heritage collection.
    url:
    link-reference: preservation
    description: Digital preservation requires adequate planning, description and modes of access. During this session, participants will be introduced to the principles of sound collection development and learn how to arrange and describe content so that it is legible and discoverable to users. Using the site built during the previous session, participants will begin to create a digital heritage collection.
  - name: Participatory Heritage
    url: 
    link-reference: participation
    description: Digital technologies have created new possibilities for the public to engage with and co-create heritage resources. This workshop will explore different models for engaging the public in heritage work with a particular focus on the participatory archive. In addition to surveying the field, participants will learn how to use digital tools like Scripto and OHMS to engage the public in their work as well how to integrate these tools into their selected publishing platform.
  - name: Visualizing Heritage
    url: 
    link-reference:  visualization
    description: Data visualization is a technique that researchers and creative practitioners use to analyze and communicate information through graphical means. In this session, participants will discuss the characteristics of effective graphical displays and practice visualizing the spatial and social relations of selected heritage resources.
  - name: Augmented Heritage
    url: 
    link-reference: ar
    description: This session examines how mobile Augmented Reality (AR) can be employed to increase and diversify public engagement with heritage. Starting with an overview of AR and existing heritage apps, participants will be introduced to some of the basic principles of app development with Swift.   
  - name: Project Planning
    link-reference: project
    description: What separates projects that turn into something from those that stall out and go nowhere is the formulation (and constant revision and adaptation) of a reasonable, informed, and purposeful project plan. During this session, participants will be introduced to sound project development and management practices. They will also have time to work independently or—if desired—in groups to draft a proposal for a digital heritage project for research or teaching.
  - name: Presentations and Discussion
    link-reference: presentations
    description: In the final session, participants will present their project proposals and we will discuss how to build on the experience of the institute to create a sustainable community of digital humanities practice at A-State.
# this tells Jekyll to build the site in the "docs"
# directory, which is ideal for hosting by GitHub Pages
destination: docs


# Files that won't be included in the compiled version of the site
exclude:
  - '*.sh'
  - CNAME
  - bower_components
  - node_modules
  - _images
  - '.*'
  - 'gulpfile.js'
  - 'build_vendor.js'
  - 'get_data.js'
  - 'README.md'

# _config.stage.yml overwrites these options when you run locally
future: false
limit_posts: 10 # Only make the last 10 posts so generating isn't slow
show_drafts: false

#required by github-pages
lsi: false # Disables the more accurate related posts
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
